### ISSUE TITLE
Deploy sort order of security assets 

### ISSUE THREAD

**Issue by jmakeig** [rjrudin/ml-app-deployer#114]
I've got a [project](https://github.com/jmakeig/mltap/tree/issue-10/config) that just needs security set-up. However, when I do a plain vanilla `gradle mlDeploy` it starts with the privileges. Of course privileges depend on roles, so the deploy errors out. How do I tell mlDeploy to start with roles? The order in the plugin script looks correct 

### build.gradle
```groovy
buildscript {
  repositories {
    mavenCentral()
    mavenLocal()
    jcenter()
  }
  dependencies {
    classpath "com.marklogic:ml-gradle:2.3.2"
  }
}

apply plugin: 'com.marklogic.ml-gradle'
```

### grade.properties

```
mlHost=localhost
mlAppName=mltap
mlAdminUsername=admin
mlAdminPassword=********
mlConfigDir=config/marklogic
```

### Directory Structure
```
|-config
  |-marklogic
   |---security
     |---amps
      mltap-runner.json
     |---privileges
      mltap-runner.json
     |---roles
      mltap-internal.json
      mltap-tester.json
     |-----users
       tester.json
```

### Error

```
<snip/>
Executing command [com.marklogic.appdeployer.command.groups.DeployGroupsCommand] with sort order [5]
Finished executing command [com.marklogic.appdeployer.command.groups.DeployGroupsCommand]

Executing command [com.marklogic.appdeployer.command.security.DeployPrivilegesCommand] with sort order [10]
Processing files in directory: /Users/jmakeig/Workspaces/mltap/config/marklogic/security/privileges
Processing file: /Users/jmakeig/Workspaces/mltap/config/marklogic/security/privileges/mltap-runner.json
Sending XML GET request as user with admin role 'admin' to path: /manage/v2/privileges
Creating privilege: mltap-runner
Sending JSON POST request as user with admin role 'admin' to path: /manage/v2/privileges
POST request for "http://localhost:8002/manage/v2/privileges" resulted in 400 (Bad Request); invoking error handler
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"400", "status":"Bad Request", "messageCode":"MANAGE-INVALIDCONFIG", "message":"MANAGE-INVALIDCONFIG: (err:FOER0000) Invalid server configuration:  Cannot create privilege in database"}}
:mlDeployApp FAILED
```

I think the problem might be in the [command sorting constants](https://github.com/rjrudin/ml-app-deployer/blob/master/src/main/java/com/marklogic/appdeployer/command/SortOrderConstants.java#L7-L15).

**Comment by rjrudin** [comment]
Roles can refer to privileges, and privileges can refer to roles. I chose to make roles slightly more important than privileges, so privileges are expected to not refer to custom roles, but roles can refer to standard and custom privileges. I also like the ability to look at a role file and see everything it's got.

I don't know of a good way to support both privileges referring to custom roles and roles referring to custom privileges.

**Comment by jmakeig** [comment]
It works if I deploy in two passes:

1. Move the privilege that depends on the custom role out of the config directory
1. Run `gradle mlDeploy`
1. Move the privilege back into the config directory
1. Run `gradle mlDeploy` again

Perhaps the config directory could be configured as a list by file name, similar to how you’d order individual roles in the `roles` directory.

**Comment by jmakeig** [comment]
I think I figured it out:

Create the privilege without any roles
```json
{
  "privilege-name": "mltap-runner",
  "action": "http://github.com/jmakeig/mltap/runner",
  "kind": "execute",
  "role": [ ]
}
```

Add the privilege to the `privilege` array
```json
{
  "role-name": "mltap-tester",
  "description": "",
  "privilege": [
    {
      "action": "http://marklogic.com/xdmp/privileges/xdbc-eval",
      "kind": "execute",
      "privilege-name": "xdbc:eval"
    },
    {
      "action": "http://github.com/jmakeig/mltap/runner",
      "kind": "execute",
      "privilege-name": "mltap-runner"
    }
  ]
}
```

This seems to work in a single pass.
