### ISSUE TITLE
How do I prevent the default app servers from being created?

### ISSUE THREAD

**Issue by jmakeig** [rjrudin/ml-app-deployer#115]
I’m using [ml-gradle](/rjrudin/ml-gradle) to configure my MarkLogic instance. However, I just want security settings (roles, users, amps, privileges), not a full-blown “app”. Is there a way to prevent the default behavior that creates databases and app servers?

**Comment by sastafford** [comment]
Here is an example:

[MarkLogicSimpleJobRepositoryAppDeployer](https://github.com/sastafford/marklogic-spring-batch/blob/master/core/src/main/java/com/marklogic/spring/batch/core/repository/MarkLogicSimpleJobRepositoryAppDeployer.java)

[MarkLogicSimpleJobRepositoryConfig.java](https://github.com/sastafford/marklogic-spring-batch/blob/master/core/src/main/java/com/marklogic/spring/batch/core/repository/MarkLogicSimpleJobRepositoryConfig.java)

**Comment by jmakeig** [comment]
@sastafford Not to be dense, but I’m not sure how to apply your examples above to [my ml-gradle set-up](https://github.com/jmakeig/mltap/tree/develop/config).

**Comment by rjrudin** [comment]
Caught me with a few minutes before a meeting - https://github.com/rjrudin/ml-gradle/tree/master/examples/no-appservers-project

You also have the option of removing all commands from mlAppDeployer and adding only the ones you want. ml-gradle starts with a set of commands and default behavior that should be reasonable for the majority of projects. You can customize it to do whatever you want though.

**Comment by jmakeig** [comment]
Yup, I think that's it. Thanks, @rjrudin. I think my problem is that I just haven’t invested the effort to understand *how* ml-app-deployer and ml-gradle work. I’m still at the exclusively copy-pasta stage.
