### ISSUE TITLE
Ingest XQuery workspaces to MarkLogic

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-app-deployer#16]
As a user
I want to TITLE
So that I can share Query Console workspaces with other developers

Routinely, I want to share a bunch of xquery snippets with customers and have that show up automatically in a qc workspace.  This would be a really neat feature for starters.  

/project
  /src
    /test
      /xqy
        /qconsole
          /<workspace-name>
            query1.xqy
            query2.js
            :

**Comment by rjrudin** [comment]
Scott - where do those get ingested into? The app-services database? I agree, this sounds like a nice feature, I just don't know where they should go yet.

**Comment by rjrudin** [comment]
Also, I think "/data" is a good standard top-level directory in a project structure for holding version-controlled data files that aren't part of the runtime for an application. How about "/data/qc-workspaces" as a directory?

**Comment by TammyHale** [comment]
I have xquery code for saving a qc workspace to disk. I do this somewhat regularly. It's currently on the hs but it would be trivial to retype it / rewrite it to ingest. OTH, do you see this as being different from the import workspace functionality in qconsole? If not, we could re-use MarkLogic server code in Modules/MarkLogic/appservices/qconsole/qconsole-model. The function is called import-workspace.

**Comment by rjrudin** [comment]
I hadn't thought about how best to export the workspace documents - or when a user would do it. 

At least  for importing them, the main requirement is that we don't impose any new requirements - e.g. an XDBC server - on the developer's application. Ideally it can be done via an XCC call to port 8000 server, which now exposes an XDBC interface.

**Comment by rjrudin** [comment]
This is now in ml-javaclient-util
