### ISSUE TITLE
Predefined search options need to be loaded into the http-test appserver

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-app-deployer#17]
I'm writing some unit tests using the QueryManager and predefined search options.  Apparently, the namespace uri contains the name of the appserver.  

/Default/<app-name>/rest-api/options/default.xml

If I run the QueryManager Java Client API class against the test app server, then it is going to look for the following uri.

/Default/<app-name>-test/rest-api/options/default.xml

The options are executed against the app server and not the test app server.

**Comment by rjrudin** [comment]
Taking a look at this now, should be able to devise a fix for this in ml-gradle's sample-project.

**Comment by rjrudin** [comment]
LoadModulesCommand supports this now - the above test commit includes a test for it.
