### ISSUE TITLE
Assign permissions to assets 

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-app-deployer#22]
As a user
I want to TITLE
So that I can allow users to execute assets without having to have the rest-admin role

http://docs.marklogic.com/REST/PUT/v1/ext/[directories]/[asset]
2nd parameter - perm:{role}*

**Comment by rjrudin** [comment]
Assuming you're using LoadModulesTask - e.g. mlLoadModules - you can configure this already:

mlLoadModules.assetRolesAndCapabilities=(comma-delimited roles and capabilities)

See the source for LoadModulesTask in ml-gradle. 

I'll keep this open for the 2.0 milestone though to ensure this is still possible.

**Comment by rjrudin** [comment]
Also, the permissions on modules loaded via the REST API default to read/update for rest-admin and execute for rest-extension-user. So you shouldn't need a rest-admin user.
