### ISSUE TITLE
Add ability to override the modules db in LoadModulesCommand

### ISSUE THREAD

**Issue by paxtonhare** [rjrudin/ml-app-deployer#69]
From what I can tell you can theoretically do this by setting modulesDatabaseName in AppConfig. But for the life of me I can't get gradle to recognize my custom value.

Ultimately what I want to do is be able to deploy sjs and xqy modules into the "Modules" database. I'm trying to stand up an app against a vanilla, default ML instance against 8000 w/o having to bootstrap.

I've tried this in build.gradle:

```groovy
apply plugin: 'ml-gradle'

ext {

    mlAppConfig {
        modulesDatabaseName = "Modules"
    }
}
```

But no luck.

@rjrudin suggested I try rest-api.json but it didn't seem to help.

```json
{
  "rest-api": {
    "modules-database": "Modules"
  }
}
```

**Comment by rjrudin** [comment]
Hey Paxton - I made this sample project to verify that you can set mlAppConfig.modulesDatabaseName to "Modules" (note I had to add a line of code to the Gradle file to tell ml-gradle not to delete the modules database on undeploy):

https://github.com/rjrudin/ml-gradle/tree/master/examples/use-modulesdb-project

But it sounds like you need something a bit different - you don't want to create a REST API server at all, you just want to use port 8000? The DeployRestApiServersCommand doesn't have a "disabled" property on it (I'm going to open a ticket for that), but you can remove it from the set of commands that mlAppDeployer uses:

ext {
    mlAppConfig {
        modulesDatabaseName = "Modules"
    }
  mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand("DeployRestApiServersCommand"))
}

**Comment by paxtonhare** [comment]
Sweet. I'll give this a try. Thanks for your help.
