### ISSUE TITLE
Scheduled database backups still remain after running mlUndeploy

### ISSUE THREAD

**Issue by abefekadu** [rjrudin/ml-app-deployer#79]
When running mlUndeploy scheduled database backup tasks remain even though the database that it is supposed to be backing up is no longer around. The code should check to see if there are any scheduled database tasks and remove them.

**Comment by rjrudin** [comment]
Where do you see the scheduled backups? I just created a minimal app with ml-gradle, and then I manually added a scheduled backup. It appeared in the properties endpoint for the database I created. I didn't find any other evidence of it - there's no scheduled task or anything. So when the app is undeployed, and the database is deleted, the scheduled backup seems to be gone as well.

**Comment by rjrudin** [comment]
I haven't been able to reproduce this issue - please reopen if you can reproduce it.
