### ISSUE TITLE
when running mlUndeploy forest replicas are still around

### ISSUE THREAD

**Issue by abefekadu** [rjrudin/ml-app-deployer#80]
After running mlUndeploy forest replicas that were created should be removed as part of running this task.

**Comment by rjrudin** [comment]
This shouldn't be difficult to handle - ForestManager has a getReplicaIds(forestIdOrName) method which can be used to find all the replicas for a given forest. 

Forests are almost always deleted via DeployDatabaseCommand - by default, on undo, it deletes all the forests for a database. 

So I think the solution here is to modify that command to do the following (assuming that forestDelete is set to true on the command):

1. Get all the forest IDs for a database
1. For each forest ID, get its replica IDs ,and delete each of those forests
1. Delete the database (as is currently done)

**Comment by rjrudin** [comment]
Including this in 2.0 release
