### ISSUE TITLE
Allow caller to set rest api file path in DeployRestApiServersCommand

### ISSUE THREAD

**Issue by paxtonhare** [rjrudin/ml-app-deployer#91]
https://github.com/rjrudin/ml-app-deployer/blob/master/src/main/java/com/marklogic/appdeployer/command/restapis/DeployRestApiServersCommand.java#L44

I want to be able to set the file path so that ml-app-deployer will read my custom rest server json instead of the default.

My use case is to create 2 http REST api servers

**Comment by rjrudin** [comment]
@paxtonhare How does this look, where my-custom-rest-api.json is in the root of ml-config?

    mlAppDeployer.getCommand("DeployRestApiServersCommand").setRestApiFilename("first-rest-api.json"))
    mlAppDeployer.add(new com...DeployRestApiServersCommand("second-rest-api.json"))

The files unfortunately have to be in the root of ml-config... I'm not sure why I didn't choose to put them in ml-config/rest-apis.

**Comment by rjrudin** [comment]
@paxtonhare I'm including this in the 2.1.0 release of ml-app-deployer - the test indicates that it's working, though I'm not sure if it's the right design. I can do a patch release though to adjust the behavior.

**Comment by paxtonhare** [comment]
@rjrudin should this same change be made for UpdateRestApiServersCommand? If so I can create another ticket.

**Comment by rjrudin** [comment]
@paxtonhare Ack, yes... I'll write up the ticket, thanks for the catch. I forgot about how a REST API server has the 2 separate endpoints - one for creating, one for updating.
