### ISSUE TITLE
AlertRules and AlertActions have the same SortOrder

### ISSUE THREAD

**Issue by peetkes** [rjrudin/ml-app-deployer#95]
The AlertRules and AlertActions commands have the same sort order. Is that by design?

Seen DeployAlertRulesCommand.java on line 18:

    public DeployAlertRulesCommand() {
        setExecuteSortOrder(SortOrderConstants.DEPLOY_ALERT_ACTIONS);
    }

Shouldn't that be SortOrderConstants.DEPLOY_ALERT_RULES?

**Comment by rjrudin** [comment]
@peetkes Thanks for the catch, I've made a fix on the dev branch. I've used the alert commands for a few months now without any issues, so I don't think this should have any negative impact, but it'll be fixed in 2.2.0 nonetheless.
